add mongo connection
InTechMOM/team-2-back pull request #2
Opened 2023-04-17 19:04 UTC by Julys-esp

Se agrego la conexión a mongo, los datos de la URL, nombre de la DB y colección quedaron vacíos para agregar los que se vayan a usar en su momento.

2023-04-19 05:35 UTC, KarenEchavarria requested changes

2023-04-21 22:48 UTC, Julys-esp commented on src/app.js
> +const uri='';
Ya agregue la URI y realice algunos cambios

2023-04-28 23:44 UTC, Julys-esp commented
Realice nuevos cambios, ya conecta sin problema a la DB en Mongo
![image](https://user-images.githubusercontent.com/125158160/235270432-cab1180c-99b5-4f8d-9b86-04ece4e0ae18.png)

2023-05-09 21:16 UTC, KarenEchavarria approved these changes

2023-05-09 21:16 UTC, merged